
dist: xenial

sudo: required

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  # - "pypy-5.7.1"

branches:
  only:
    master


# Install dependencies
before_install:
  - FLORENCEPATH=$(pwd)
  - echo $FLORENCEPATH
  - sudo apt-get update --fix-missing
  - sudo apt-get install curl
  # Install BLAS libraries
  - echo -ne '\n' | sudo apt-get install gfortran libblas-dev liblapack-dev libatlas-base-dev libopenblas-* libsuitesparse-dev swig
  # pypi packages - install before installing PostMesh
  - cd $FLORENCEPATH
  - travis_wait 50 pip install -r "requirements.txt"
  # Install Eigen
  - EIGENVERSION=3.3.8
  - cd ~
  - curl https://gitlab.com/libeigen/eigen/-/archive/$EIGENVERSION/eigen-$EIGENVERSION.tar.bz2 -o eigen.tar.bz2
  - tar -xvf eigen.tar.bz2
  - sudo mv eigen-$EIGENVERSION /usr/local/include/eigen/
  # Install OpenCascade
  - echo -ne '\n' | sudo apt-get install liboce-*
  # PostMesh
  - pip install PostMeshPy
  # Fastor
  - git clone https://github.com/romeric/Fastor
  - sudo mv Fastor /usr/local/include/Fastor/
  # update the cache
  - sudo ldconfig

install:
  # build florence modules
  - cd $FLORENCEPATH; echo -ne '\n' | python setup.py build

script:
  # Run florence test suite
  - cd ~
  - export PYTHONPATH=$FLORENCEPATH:$PYTHONPATH
  - cd $FLORENCEPATH/tests; nosetests -x --with-coverage --cover-package=Florence test.py

after_success:
  - coveralls

notifications:
  email: false
